### ISSUE TITLE
Please delete logo

### ISSUE THREAD

**Issue by hotchemi** [a1018875550/PermissionDispatcher#1]
@a1018875550 You should delete logo. That is what I prepared.

**Comment by MichaelJokAr** [comment]
Sorry,I delete now

**Comment by MichaelJokAr** [comment]
Could I pull this for your PermissionsDispatcher, I found the judgment for "Xiaomi" phone only chage the "PermissionUtils" others is same;And I test it,it's work for "Xiaomi" phone

**Comment by hotchemi** [comment]
No

**Comment by MichaelJokAr** [comment]
Because there has a Japanese friends suggest me  pull request to original PermissionsDispatchers for many users.
#2

**Comment by hotchemi** [comment]
Ah you mean code, pr is okay but I'm not sure I can merge, since I don't understand the diff.
