### ISSUE TITLE
可以解释一下小米和官方在权限处理上的区别吗?

### ISSUE THREAD

**Issue by ZJsnowman** [a1018875550/PermissionDispatcher#4]
您好,能够解释一下小米在权限处理上有什么区别吗?我这边用的是google 的easyPermission  .我觉得好不错,最近反馈在小米手机上好像有点问题.到具体区别我暂时还没有弄清楚.希望阁下能够分享一下,需要在那一块进行特殊处理?

**Comment by MichaelJokAr** [comment]
参考<a href="https://github.com/a1018875550/PermissionDispatcher/blob/master/library/src/main/android/org.jokar.permissiondispatcher.library/PermissionUtils.java">PermissionUtils. hasSelfPermission ()</a>对小米主要是增加判断了AppOpsManager，仅在6.0及以上有作用
